name: Daily Commit

on:
  schedule:
    - cron: '0 5 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install DateTime

    - name: Run Python Script
      run: |
        python main.py

    - name: Commit Changes
      
      run: |
        git config --global user.email "suvan.gowrishanker.204@gmail.com"
        git config --global user.name "greeenboi"
        git commit -am "Daily Commit bois"
        git push